### ISSUE TITLE
Salmon > RapClust pipeline compatibility 

### ISSUE THREAD

**Issue by Quarkins** [COMBINE-lab/RapClust#14]
Hi there good RapClust developers, thanks for this great tool. I am very much looking forward to using it.

I want to use it to cluster conigs made from long read data (PacBio) which i assemble with Trinity (but also with Canu as an alternative). I wanted to use Salmon (rather than sailfish, since that is what i had installed and to be frank i am not quite sure the differences) to index and quantify the transcript abundances to then plug into RapClust. Rapclust mentions that you can use either Salmon or Sailfish. 

When running in RapClust the first error i get is that <dir>/aux/eq_classes.txt doesn't exist. Well that is a simple fix since Salmon produced dir "aux_info" rather than "aux" (you may want to change the code to check in both directories). But i just renamed the folder and tried running again. 

Then i run into this error:

INFO:root:Building multiple alignment graph
file: transcripts_quant/aux/eq_classes.txt; # tran = 13112; # eq = 14062
Traceback (most recent call last):
  File "/group/bioi1/anthonyh/anaconda3/bin/RapClust", line 89, in <module>
    processQuant()
  File "/mnt/storage/anthonyh/anaconda3/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/storage/anthonyh/anaconda3/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/mnt/storage/anthonyh/anaconda3/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/storage/anthonyh/anaconda3/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/group/bioi1/anthonyh/anaconda3/bin/RapClust", line 54, in processQuant
    eqnet.buildNetFile(sampleDirs, netFile, cutoff)
  File "/mnt/storage/anthonyh/anaconda3/lib/python3.5/site-packages/rapclust/eqnet.py", line 39, in buildNetFile
    for i in xrange(numTran):
NameError: name 'xrange' is not defined

Looking into that error it appears that xrange isn't defined in python3.  So i don't know whether you want to specify to users that they neeed python 2.7 or whether you want to make it compatible with python3, but i thought i should perhaps point those things out as they may be helpful!

Cheers,
Anthony

**Comment by Quarkins** [comment]
Sorry for the second comment, just to add, i am using the binary version of Salmon (0.72). 
I managed to get everything working once i switched to py2.7 and renamed the aux_info -> aux.
Running salmon with the --dumpEq flag to get the equivalnce classes.

Perhaps one could put a flag in the config.yaml specifying whether the user ran salmon or sailfish and hence whether to look for the equivalence class file in aux/aux_info.

Just some ideas, but thanks again for this great tool, having used alot of Corset before it is fun to try this speedy variation!

**Comment by k3yavi** [comment]
@Quarkins Thanks for using our tool and giving useful comments.
We have resolved most of these in our latest pip release.
