### ISSUE TITLE
lost contigs along the way ?

### ISSUE THREAD

**Issue by TristanLefebure** [COMBINE-lab/RapClust#17]
Hi,

I have a trinity assembly that contains 215578 contigs:
```
[tristan@umr5023-proasellus PCG6_rapclust] grep -c '>' ../trinity_assembly.fa
215758
```
I ran Salmon, and got expression for these 215578 contigs:

```
[tristan@umr5023-proasellus PCG6_salmon_transcripts_quant] wc -l quant.sf
215759 quant.sf
```
But RapClust only returns cluster assigment for 134922 contigs:

```
[tristan@umr5023-proasellus PCG6_rapclust] wc -l mag.flat.clust
134922 mag.flat.clust
```
How come?

Thanks!

**Comment by laraib85** [comment]
Hi,

RapClust removes contigs that have less than 10 reads mapping to them. That's why the drop in total contig count.

**Comment by TristanLefebure** [comment]
thanks for the info !
