### ISSUE TITLE
index out of bounds error 

### ISSUE THREAD

**Issue by jesgomez** [COMBINE-lab/RapClust#7]
Hi,
I'm trying to run Sailfish + Rapclust in my data. I had some RNAseq samples from several conditions and I assembled with Trinity each condition separately, obtaining 4 different transcriptomes. Now, I'm trying to cluster them together in order to get a unique transcriptome for the specie (instead of 1 per each condition), so I concatenated all the transcriptomes in a single multifasta file and tried to run sailfish and Rapclust as I usually do. I indexed the combined transcriptome with sailfish and quantified each sample without getting any error. But when I run Rapclust, I get the following error:
Traceback (most recent call last):
  File "/apps/RAPCLUST/0.1/bin/RapClust", line 89, in <module>
    processQuant()
  File "/apps/RAPCLUST/0.1/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/apps/RAPCLUST/0.1/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/apps/RAPCLUST/0.1/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/apps/RAPCLUST/0.1/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/apps/RAPCLUST/0.1/bin/RapClust", line 54, in processQuant
    eqnet.buildNetFile(sampleDirs, netFile, cutoff)
  File "/apps/RAPCLUST/0.1/lib/python2.7/site-packages/rapclust/eqnet.py", line 100, in buildNetFile
    if (diagCounts[i] > cutoff):
IndexError: index 1423084 is out of bounds for axis 0 with size 1423084
Do you know why is this happening? How can I fix this error?
Thanks a lot,
Jèssica

**Comment by keyavi** [comment]
This error looks strange, in my opinion what it means is the length of **TPM** and **NumReads** columns in sailfish quantification output file are different, which doesn't make sense.
Can you forward your data somewhere so that I can check?

**Comment by jesgomez** [comment]
Sorry for the delay in my response. I've been making some more tests and it
seems to me that the problem could be because I'm trying to combine
transcriptomes obtained from different runs of Trinity. Could that be? When
I run it on the different transcriptomes separately it works fine, as well
as with other data. But when I run it in the whole set of transcripts
(after doing a cat */Trinity.fasta > all_transcripts.fa) it gives the
error.
I make the sailfish index on this all_transcripts.fa file and then quantify
each sample separately.
Thanks for your help.



2016-07-27 19:35 GMT+02:00 Avi Srivastava <notifications@github.com>:

**Comment by keyavi** [comment]
You are right, RapClust is designed with the assumptions or rather motivation that quantification information is already present from different conditions individually. However, you should not get error like this while running Sailfish (i.e. different number of *TPM* and *Num Reads* in .sf file).
One problem which we can think of (thanks to @laraib85) could be that combining transcriptome (i.e. ```cat */Trinity.fasta > all_transcripts.fa``) can result in multiple entries with the same transcript ids (depending on the assembler you use).
Please check your file all_transcripts.fa for redundant transcript id if present try renaming them.
Let us know how does this work out.

**Comment by jesgomez** [comment]
Hi again,
You were right, the problem were the redundant ids... I gave uniq ids to
each transcript and repeated the process, and it worked! So, thank you for
the advice.

2016-08-08 5:45 GMT+02:00 Avi Srivastava <notifications@github.com>:

**Comment by k3yavi** [comment]
Glad to hear.
